### ISSUE TITLE
Material images can't be seen in Planner

### ISSUE THREAD

**Issue by Beratreides** [The-Intelligent-One/FGO-Tracker#105]
![image](https://user-images.githubusercontent.com/93325867/139251917-168b5674-d807-441d-adba-0aecc46855b0.png)

**Comment by Beratreides** [comment]
It seems data>cache>images is filled with empty images. I downloaded an old version and copied images from old to new.

**Comment by The-Intelligent-One** [comment]
Oh god, why. Guess this goes the pile of "why is it like this, I have to fix this immediately" that needs to be worked on

**Comment by The-Intelligent-One** [comment]
Found the problem: when trying to load images from the cache, the app forgot to check whether or not those images existed, and because of that it just tried using nothing as the icons, which it then saved.
