### ISSUE TITLE
Program crashes on launch

### ISSUE THREAD

**Issue by LeonardoDeQuirm** [The-Intelligent-One/FGO-Tracker#107]
When trying to launch the new 3.1 beta .jar, the program instantly quits on trying to launch. 

See attached [error.log](https://github.com/The-Intelligent-One/FGO-Tracker/files/7735957/error.log)

**Comment by The-Intelligent-One** [comment]
Does it just quit? Does it give you anything else, like an error message in your face or something? I have an idea what it could be based on the error log, but I do want to make sure I have all the info I can get. Also, could you attach your data folder as well? It would be useful for testing and making sure it no longer crashes

**Comment by LeonardoDeQuirm** [comment]
Just silently quits, no error message

[data.zip](https://github.com/The-Intelligent-One/FGO-Tracker/files/7736894/data.zip)

**Comment by The-Intelligent-One** [comment]
Issue fixed, about to create release for it
