### ISSUE TITLE
Inquire about background assets

### ISSUE THREAD

**Issue by The-Intelligent-One** [The-Intelligent-One/FGO-Tracker#37]
Materials only have their icon as assets, the backgrounds are just named bronze, silver and gold. Find out if the backgrounds can be accessed as well, and use them

**Comment by squaresmile** [comment]
The frames assets are in this folder https://github.com/atlasacademy/apps/tree/master/packages/db/src/Assets/list

with the enum to file mapping [here](https://github.com/atlasacademy/apps/blob/master/packages/db/src/Component/ItemIcon.tsx#L12)

**Comment by The-Intelligent-One** [comment]
Thanks, I'll look into how I can utilize them effectively and make the app look better
